export type FlyoutE2EType =
  | 'blockchainComBalancesModal'
  | 'borrowModal'
  | 'faqModal'
  | 'interestModal'
  | 'recoveryPhraseModal'
  | 'simpleBuyModal'
  | 'welcomeModal'
  | 'whatsNewModal'
  | 'withdrawalModal'
